export const titlePriority = [
    "en",
    "ja"
];

export const langDict = {
    "al": "Albanian",
    "ar": "Arabic",
    "bd": "Bengali",
    "pt-BR": "Brazilian Portugese",
    "bg": "Bulgarian",
    "ca": "Catalan",
    "zh-x-yue": "Chinese (Cantonese)",
    "zh-x-cmn": "Chinese (Mandarin)",
    "zh-Hans": "Chinese (Simplified)",
    "zh-x-nan": "Chinese (Taiwan)",
    "zh-Hant": "Chinese (Traditional)",
    "zh": "Chinese",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "en": "English",
    "et": "Estonian",
    "fa": "Farsi",
    "fi": "Finnish",
    "fr": "French",
    "gl": "Galician",
    "ka": "Georgian",
    "de": "German",
    "el": "Greek",
    "he": "Hebrew",
    "hu": "Hungarian",
    "is": "Icelandic",
    "id": "Indonesian",
    "x-in": "Instrumental",
    "it": "Italian",
    "ja": "Japanese",
    "x-jat": "Japanese (Transcription)",
    "jv": "Javanese",
    "ko": "Korean",
    "x-kot": "Korean (Transcription)",
    "la": "Latin",
    "es-LA": "Latin American Spanish",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "my": "Malay",
    "no": "Norwegian",
    "x-other": "Other",
    "pl": "Polish",
    "pt": "Portugese",
    "ro": "Romanian",
    "ru": "Russian",
    "sr": "Serbian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "es": "Spanish",
    "sv": "Swedish",
    "ta": "Tamil",
    "tt": "Tatar",
    "th": "Thai",
    "tr": "Turkish",
    "uk": "Ukranian",
    "x-unk": "Unknown",
    "vi": "Vietnamese"
};